# Generated by Django 2.1.5 on 2019-03-12 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mosaic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128)),
                ('member_amount', models.BigIntegerField(default=0)),
                ('member_date', models.DateField()),
                ('is_update', models.BooleanField(default=False)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mosaic.AssetsCategory')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='MemberUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_date', models.DateField()),
                ('is_member', models.BooleanField(default=False)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mosaic.AssetsCategory')),
            ],
            options={
                'ordering': ['-c_time'],
            },
        ),
        migrations.AddIndex(
            model_name='memberupdate',
            index=models.Index(fields=['c_time'], name='member_memb_c_time_26eb2f_idx'),
        ),
        migrations.AlterIndexTogether(
            name='memberupdate',
            index_together={('member_date', 'is_member', 'c_time')},
        ),
        migrations.AddIndex(
            model_name='memberinfo',
            index=models.Index(fields=['c_time'], name='member_memb_c_time_92c4a2_idx'),
        ),
        migrations.AlterIndexTogether(
            name='memberinfo',
            index_together={('username', 'member_amount', 'member_date', 'is_update', 'c_time')},
        ),
    ]
