# Generated by Django 2.1.5 on 2019-03-12 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OfficialSharePrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=16)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('u_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PersonalGain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_bet', models.BigIntegerField(default=0)),
                ('grade_one', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('grade_two', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('grade_three', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('grade_four', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('grade_five', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('u_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['c_time'],
            },
        ),
        migrations.CreateModel(
            name='TransactionHour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('close_desc', models.CharField(max_length=255)),
                ('is_maintain', models.BooleanField(default=False)),
                ('maintain_desc', models.CharField(default='', max_length=255)),
                ('start_a', models.TimeField()),
                ('end_a', models.TimeField()),
                ('start_b', models.TimeField()),
                ('end_b', models.TimeField()),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('u_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
