# Generated by Django 2.1.5 on 2019-03-26 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personalgain',
            options={'ordering': ['valid_bet']},
        ),
        migrations.RemoveField(
            model_name='transactionhour',
            name='end_b',
        ),
        migrations.RemoveField(
            model_name='transactionhour',
            name='start_b',
        ),
    ]
