# Generated by Django 2.1.5 on 2019-03-12 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BuyDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField(auto_now_add=True)),
                ('buying_shares', models.IntegerField(default=0)),
                ('spend_coding', models.BigIntegerField()),
                ('operating_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-operating_time'],
            },
        ),
        migrations.CreateModel(
            name='LotteryReceiptDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receive_bonus', models.DecimalField(decimal_places=2, default=0.0, max_digits=16)),
                ('pickup_time', models.DateTimeField(auto_now_add=True)),
                ('is_send', models.BooleanField(default=False)),
                ('send_time', models.DateTimeField(null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=128, unique=True)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['c_time'],
            },
        ),
        migrations.CreateModel(
            name='MemberAssets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_assets', models.BigIntegerField()),
                ('residual_assets', models.BigIntegerField()),
                ('buying_shares', models.IntegerField(default=0)),
                ('selling_shares', models.IntegerField(default=0)),
                ('holding_shares', models.IntegerField(default=0)),
                ('available_lottery', models.DecimalField(decimal_places=2, default=0.0, max_digits=16)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mosaic.AssetsCategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mosaic.Member')),
            ],
            options={
                'ordering': ['-c_time'],
            },
        ),
        migrations.CreateModel(
            name='SellDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField(auto_now_add=True)),
                ('selling_shares', models.IntegerField(default=0)),
                ('official_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('personal_gain', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('earn_prize', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('operating_time', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mosaic.AssetsCategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mosaic.Member')),
            ],
            options={
                'ordering': ['-operating_time'],
            },
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['c_time'], name='mosaic_memb_c_time_48ce02_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['user_name'], name='mosaic_memb_user_na_ef68a0_idx'),
        ),
        migrations.AlterIndexTogether(
            name='member',
            index_together={('user_name', 'c_time')},
        ),
        migrations.AddField(
            model_name='lotteryreceiptdetails',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mosaic.AssetsCategory'),
        ),
        migrations.AddField(
            model_name='lotteryreceiptdetails',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mosaic.Member'),
        ),
        migrations.AddField(
            model_name='buydetails',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mosaic.AssetsCategory'),
        ),
        migrations.AddField(
            model_name='buydetails',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mosaic.Member'),
        ),
        migrations.AlterIndexTogether(
            name='assetscategory',
            index_together={('name', 'c_time')},
        ),
        migrations.AddIndex(
            model_name='memberassets',
            index=models.Index(fields=['c_time'], name='mosaic_memb_c_time_f6e123_idx'),
        ),
        migrations.AlterIndexTogether(
            name='memberassets',
            index_together={('total_assets', 'residual_assets', 'buying_shares', 'selling_shares', 'holding_shares', 'available_lottery', 'c_time')},
        ),
        migrations.AddIndex(
            model_name='buydetails',
            index=models.Index(fields=['operating_time'], name='mosaic_buyd_operati_c4de1e_idx'),
        ),
        migrations.AlterIndexTogether(
            name='buydetails',
            index_together={('transaction_date', 'buying_shares', 'spend_coding', 'operating_time')},
        ),
    ]
