# Generated by Django 2.1.5 on 2019-03-17 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosaic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('people_count', models.IntegerField()),
            ],
        ),
    ]
