# Generated by Django 2.1.5 on 2019-04-18 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosaic', '0002_onlinemember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinemember',
            name='people_count',
            field=models.BigIntegerField(default=800),
        ),
    ]
